services:
  mysql:
    image: mysql:8.0
    container_name: stage_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stage_platform
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: stage_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
    ports:
      - "8082:80"
    depends_on:
      - mysql

  backend:
    build:
      context: ./stage-platform-laravel
    container_name: stage_backend
    restart: unless-stopped
    volumes:
      - ./stage-platform-laravel:/var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: stage_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./stage-platform-laravel:/var/www
      - ./stage-platform-laravel/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: stage_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - nginx

volumes:
  mysql_data: